apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-calculator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-calculator
  template:
    metadata:
      labels:
        app: basic-calculator
    spec:
      containers:
        - name: basic-calculator
          image: harbor.your-domain.com/rajottam/basic-calculator:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: basic-calculator-service
  namespace: default
spec:
  selector:
    app: basic-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP